name: Deploy to FTP

on:
  push:
    branches:
      - release

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Kök dizindeki tüm dosyaları gönderir
        server-dir: /public_html/ # FTP'deki hedef dizin
